services:
  minicloud-db:
    image: postgres:16-alpine
    container_name: minicloud-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./deploy/docker/postgres.env
    volumes:
      - minicloud-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minicloud -d minicloud"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  minicloud-db-data:

