spring:
  application:
    name: mini-cloud-control-plane
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/minicloud}
    username: ${DB_USERNAME:minicloud}
    password: ${DB_PASSWORD:minicloud}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

minicloud:
  web:
    allowed-origins: ${MINICLOUD_WEB_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://localhost:5500,http://127.0.0.1:5500}
  kubernetes:
    kubectl-bin: ${KUBECTL_BIN:kubectl}
    wait-timeout-seconds: ${K8S_WAIT_TIMEOUT_SECONDS:120}
    postgres:
      image: ${POSTGRES_IMAGE:postgres:16-alpine}
      port: ${POSTGRES_PORT:5432}
