apiVersion: v1
kind: Pod
metadata:
  name: {{POD_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{INSTANCE_NAME}}
spec:
  containers:
    - name: postgres
      image: {{POSTGRES_IMAGE}}
      ports:
        - containerPort: {{POSTGRES_PORT}}
      env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{SECRET_NAME}}
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{SECRET_NAME}}
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{SECRET_NAME}}
              key: POSTGRES_PASSWORD
      readinessProbe:
        tcpSocket:
          port: {{POSTGRES_PORT}}
        initialDelaySeconds: 5
        periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  selector:
    app.kubernetes.io/instance: {{INSTANCE_NAME}}
  ports:
    - port: {{POSTGRES_PORT}}
      targetPort: {{POSTGRES_PORT}}
      protocol: TCP
